name = "repo-name-whisperer"
compatibility_date = "2024-01-14"

[build]
command = "npm run build"
pages_build_output_dir = "dist"

[site]
bucket = "./dist"

# Functions configuration
[functions]
directory = "functions"  

# API keys and other secrets should be set using wrangler secrets
[vars]